---

 - name: Matt Gagne
   github: mpgagne
   twitter: mpgagne
   gravatar: mpgagne@gmail.com
   bio: "A lover of all things science and technology, Matt has had a long history with both. While his favorite job was probably that year he got to make computer games for monkeys to test their learning abilities, he has since gone on to work in medical research and has a masters in bioimaging technology. Being unable to escape school, Matt is currently working on getting his PhD in Medical Physics at UMass Lowell. Like any good geek, he has done his share of computer and IT work along the way and is trying to become a better amateur coder than he currently is."

 - name: Adam Jarret
   github: adamjarret
   twitter: adamjarret
   gravatar: adam.jarret@gmail.com
   bio: "A long time developer and avid indoorsman, Adam's fondness for minutiae makes him a formidable trivia opponent. Coding is his passion; he revels in making repetitive tasks easier. While he's most comfortable hunched over his laptop at home, a recent relocation to Honolulu has redoubled a latent love of distance cycling. He’s sort of well travelled (at least in Europe) but would be fairly useless in any kind of survival situation. If you want to get an action movie marathon or table top game night going, he’s your guy."

 - name: Matt Surabian
   github: mattsurabian
   twitter: mattsurabian
   gravatar: matt@mattsurabian.com
   bio: "A known space hater, Arch Linux user, and lover of reality television, Matt has been described by friends and enemies alike as: <em>\"the smartest idiot they've ever met.\"</em> Matt is currently the account manager at <a href=\"http://www.bocoup.com\" target=\"_blank\">Bocoup</a> in Boston and has worked in the tech industry for 10 years doing front-end development and infrastructure administration. He believes computers need to be put in their place (lest we have a robot uprising) and loves helping other people learn to do that. Matt has an active interest in cryptography and loves all things security related."